---
abstract: 'Interface to HTTP Keyserver Protocol (HKP)'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  Module::Signature: '0'
  Socket: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-HKP
requires:
  Carp: '0'
  LWP::UserAgent: '6.05'
  URI: '1.60'
  URI::Escape: '3.31'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/zurborg/libwww-hkp-perl/issues
  homepage: https://github.com/zurborg/libwww-hkp-perl
  repository: https://github.com/zurborg/libwww-hkp-perl.git
version: '0.04'
x_contributors:
  - 'David Zurborg <post@david-zurb.org>'
  - 'Sergey Romanov <sromanov-dev@yandex.ru>'
